export const userData = [
  {
    name: "Jan",
    "Active User": 1280,
  },
  {
    name: "Feb",
    "Active User": 1780,
  },
  {
    name: "March",
    "Active User": 2780,
  },
  {
    name: "April",
    "Active User": 4780,
  },
  {
    name: "May",
    "Active User": 1890,
  },
  {
    name: "June",
    "Active User": 3390,
  },
  {
    name: "July",
    "Active User": 3490,
  },
  {
    name: "Aug",
    "Active User": 1490,
  },
  {
    name: "Sept",
    "Active User": 2390,
  },
  {
    name: "Oct",
    "Active User": 5490,
  },
  {
    name: "Nov",
    "Active User": 3490,
  },
  {
    name: "Dec",
    "Active User": 1490,
  },
];

export const userRows = [
  {
    id: 1,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 2,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 3,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 4,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 5,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 6,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 7,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 8,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 9,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 10,
    userName: "John Snow",
    avatar: "https://images7.alphacoders.com/650/650008.jpg",
    email: "john@gmail.com",
    status: "active",
    transaction: "$120.34",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: "https://images7.alphacoders.com/650/650008.jpg",
    stock: 123,
    status: "active",
    transaction: "$120.34",
  },
];
